web: gunicorn -w ${WSGI_PROCESSES:-5} {{cookiecutter.project_slug}}.wsgi --log-file -
{% if cookiecutter.use_celery == 'y' -%}
worker: celery -A {{cookiecutter.project_slug}} worker -l info -c ${WORKER_PROCESSES:-4} -B
{% endif -%}
release: python manage.py migrate --no-input
